#!/bin/bash

# Script for testing CS415/515 Assignment 1's prodcons-pthd program.
#

echo    
echo ./prodcons-pthd
./prodcons-pthd

for i in 0 1 2 8 13 16 
do
    echo    
    echo ./prodcons-pthd $i
    ./prodcons-pthd $i
done
exit 0
